### ISSUE TITLE
Clicking the browser’s back button does not work as expected

### ISSUE THREAD

**Issue by Codpoe** [tannerlinsley/react-location#103]
**Describe the bug**
Clicking the browser’s back button does not work as expected.

**To Reproduce**
1. Go to https://1u4k1.csb.app/
2. Click `Posts` link in the page
3. Click the browser’s back button
4. The page is still displaying the content of `Posts`, not the content of the `Home` page

**Expected behavior**
display the content of the `Home` page.

**Desktop (please complete the following information):**
 - Browser: chrome
 - Version: 96

**Additional context**
Oddly enough, this is fine in Chrome’s privacy mode or in the Microsoft Edge.

**Comment by tannerlinsley** [comment]
I can't reproduce. You sure you got the right link?

**Comment by Codpoe** [comment]
I’ve recorded a video to reproduce this question, and I hope this helps. And I’m a little skeptical, is there something wrong with my computer or my chrome?

https://user-images.githubusercontent.com/16123335/142755908-ba12c8b4-f165-40a0-8598-ab8f4a2b1dae.mp4

**Comment by tannerlinsley** [comment]
It could be using a cached version that’s bad, it could be a code sandbox but. You could try cloning the example to your machine and running it locally to be sure

**Comment by Schniz** [comment]
Does not reproduce on my machine either. FWIW, sometimes I had issues with browser history and CodeSandbox. I think they are patching the environment and sometimes it makes routers fail. Sort of a race condition.

**Comment by tannerlinsley** [comment]
This sound right. I’ve had issues with this I think before.

**Comment by Codpoe** [comment]
It can be replicated on my machine, even locally... I’m gonna find another machine to try.

![image](https://user-images.githubusercontent.com/16123335/142769071-91e166ba-7603-4038-9702-d15d52da416e.png)

**Comment by Codpoe** [comment]
I think the problem is the chrome plugin [`gitlab tree`](https://chrome.google.com/webstore/detail/gitlab-tree/dllpphhnoanpcnlnipopibigdoeignbb) I installed a long time ago. When I disable this plugin, the routing behavior goes back to normal. 
I’ll close this issue. I’m sorry to bother you, and thanks for your nice reply.
