### ISSUE TITLE
`package.json` specified `module` incorrectly in `react-location-devtools`

### ISSUE THREAD

**Issue by chungweileong94** [tannerlinsley/react-location#105]
**Describe the bug**
So I use Vite for my React project, and it failed the dev build and manage to find that the `module` is specified incorrectly in the package.json, or I should say the es module file doesn't seem to get bundled. I can definitely make it works by removing the `module` field as a workaround

**To Reproduce**
1. Create a React project via ViteJS
2. Setup `react-location` & `react-location-devtools`
3.  Start the dev server

**Expected behavior**
The dev server should run just normal.

**Screenshots**
![Screenshot 2021-11-21 at 10 04 52 PM](https://user-images.githubusercontent.com/15154097/142765006-3dbd9da0-830e-44d0-9ca8-fb7e1697429c.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Edge
 - Version: 95.0.1020.53

**Smartphone (please complete the following information):**
 - Device: -
 - OS: -
 - Browser: -
 - Version:-

**Additional context**
None

**Comment by tannerlinsley** [comment]
I just shipped an attempted fix that implements the imports exactly how React Query does. Hopefully it works for you :) If not, reopen/comment here.

**Comment by chungweileong94** [comment]
@tannerlinsley Thanks for the update. 

However, it doesn't seem like the issue is fixed, in fact now both the `main` & `module` is pointing to nothing. Am I missing anything?
![Screenshot 2021-11-23 at 8 55 07 PM](https://user-images.githubusercontent.com/15154097/143027698-7a3b4e53-26e9-44de-a121-1d2fd24d7979.png)
ed

**Comment by tannerlinsley** [comment]
Try again in 10 minutes

**Comment by chungweileong94** [comment]
> Try again in 10 minutes

Cool, it works perfectly now!
Thanks for the great work.
