### ISSUE TITLE
Routes are not matching because of case sensitivity

### ISSUE THREAD

**Issue by fetters5** [tannerlinsley/react-location#107]
**Describe the bug**
Routes seem to default to case sensitive and are not matching if the case is not the same.  Is there a way to make them case insensitive by default?

**To Reproduce**
1. Go to https://wuu8j.csb.app/Posts and you will see that it does not return any results

**Expected behavior**
I would expect that going to https://wuu8j.csb.app/Posts would return the same result as going to https://wuu8j.csb.app/posts 

![image](https://user-images.githubusercontent.com/3276557/142777962-c224e528-5f56-4916-bb4a-a29735d56f75.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: I tested using the latest Chrome and FF versions
 - Version: 3.28

**Comment by tannerlinsley** [comment]
I’ll add the default to be insensitive and add support for case sensitivity

**Comment by fetters5** [comment]
Awesome thank you!

**Comment by tannerlinsley** [comment]
Just shipped this!
