### ISSUE TITLE
Component set in the errorElement prop on Route is not being displayed on load error

### ISSUE THREAD

**Issue by fetters5** [tannerlinsley/react-location#112]
**Describe the bug**
the component set in errorElement is not being displayed when an error occurs in the loader function.  This also happens with the defaultErrorElement

**To Reproduce**
1. Go to (https://codesandbox.io/s/gracious-river-qy27x?file=/src/index.tsx:768-777)
2. Click on the Posts link
3. See ugly error in sandbox instead of the expected nice error

**Expected behavior**
I would expect it to render the ErrorTest component in the sandbox.  This also fails locally for me 

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 3.28

**Comment by tannerlinsley** [comment]
Definitely a bug. I’m on it.

**Comment by JoshuaAmaju** [comment]
This might be related to the issue I've been having in trying to integrate React Location with React Native. Hopeful the fix should solve that for me.

**Comment by larsvankleef** [comment]
Don't know if this is related, but when showing the `pendingElement` and the request fails or takes longer than the timeout time set in the router, the `pendingElement` stays visible. Instead of the `errorElement` of the `defaultErrorElement`

**Comment by fetters5** [comment]
If instead of throwing you return a promise rejection it works the first time and then it never goes back to that route. I cannot even get this to work in the sandbox though.  

In my case my bad router is/bad and the first time I go there it will respond with the error element, if I go to another route and try to go back to /bad it will just hang as if in a pending state

**Comment by fetters5** [comment]
@tannerlinsley I narrowed the issue down to a rejectLoader call and submitted a PR, if  I am way off base let me know but this fixed my issues with error elements

**Comment by tannerlinsley** [comment]
Should be fixed!
