### ISSUE TITLE
Difference between react-router, if any?

### ISSUE THREAD

**Issue by ghost** [tannerlinsley/react-location#12]

**Comment by tannerlinsley** [comment]
I would just use the new React Router v6 ;)

**Comment by Newbie012** [comment]
@tannerlinsley due to the last activity of this repo, would you still recommend react router over this library?

**Comment by tannerlinsley** [comment]
For the most part, yes.

Tanner Linsley

**Comment by tannerlinsley** [comment]
Please refer to the comparison: https://react-location.tanstack.com/comparison
