### ISSUE TITLE
Documentation about history is contradictory

### ISSUE THREAD

**Issue by fabienmoritz** [tannerlinsley/react-location#129]
What is the default history type, browser or hash ?
 
https://github.com/tannerlinsley/react-location/blob/06657898b0331cbd797ab050b43e645012e73fad/docs/src/pages/guides/history-types-and-location.md?plain=1#L13
https://github.com/tannerlinsley/react-location/blob/06657898b0331cbd797ab050b43e645012e73fad/docs/src/pages/guides/history-types-and-location.md?plain=1#L41

**Comment by tannerlinsley** [comment]
Fixed
