### ISSUE TITLE
useNavigation

### ISSUE THREAD

**Issue by Rujal-Duwal** [tannerlinsley/react-location#135]
On importing useNavigation() an error appear.
The screenshot is provided below.

<img width="405" alt="error" src="https://user-images.githubusercontent.com/32615873/143847023-8e2a4c07-e65e-4c4d-92b9-49c46badba4d.png">

**Comment by Suzan-Dev** [comment]
I think you're using useNavigate hook outside of the router.

**Comment by tannerlinsley** [comment]
Yep, you need to use it inside the Router component
