### ISSUE TITLE
There are cases where `errorElement` is not rendered.

### ISSUE THREAD

**Issue by ka2jun8** [tannerlinsley/react-location#156]
**Describe the bug**

When `loader` promise method of the child's route component throws an error, 
`errorElement` will not be rendered.

`errorElement` is rendered if the `match[0].status === 'rejected'`.

This `match[0]` is root component.

https://github.com/tannerlinsley/react-location/blob/62fa0a2396c9a8e8f57932fc7e390d315c0bbc08/packages/react-location/src/index.tsx#L1469

However, child route component also uses `loader`.
So I want to use the `errorElement`, when child route component loader is thrown error.

**To Reproduce**

like this;

```
    {
      element: <App />,
      loader: async () => {
          await resolvePromise();
      },
      children: [
        {
          path: "/",
          element: <Index />,
          loader: async () => {
             await rejectedPromise();
          },
          errorElement: <ErrorElement />,
        },
        ...
```

**Expected behavior**

`<ErrorElement />` is rendered when `rejectedPromise` is thrown error.

**Comment by fetters5** [comment]
What version are you using?

**Comment by ka2jun8** [comment]
Sorry, I should write it.

`"react-location": "3.2.15",`

The latest version should fix it?

**Comment by fetters5** [comment]
Yes it should fix the issue
