### ISSUE TITLE
Search matching routes that only differ in their search function gives duplicate route error

### ISSUE THREAD

**Issue by joshuabrokaw** [tannerlinsley/react-location#164]
**Describe the bug**
I'm exploring the capabilities of react-location and am trying to build a stepper using route search matching. I love the idea of being able to define a route for each step based off a search param. However, if doing something like this example below... I get an error saying it's a duplicate route. Which makes sense because not specifying a path defaults to `"*"`, but how is search matching supposed to work if the only thing changing between two routes is the search match?

```
type LocationGenerics = MakeGenerics<{
  Search: {
    step?: number;
  };
}>;

const routes: Route<LocationGenerics>[] = [
  {
    path: "/stepper",
    element: <StepperContainer />,
    children: [
      {
        search: (search) => {
          return search.step === 0;
        },
        element: <Step1 />,
      },
      {
        search: (search) => {
          return search.step === 1;
        },
        element: <Step2 />,
      },
    ],
  },
];
```

**To Reproduce**
use the above LocationGenerics and routes in a `<Router />`

**Expected behavior**
I'd expect that routes that don't produce the same match based off search matching are treated as separate routes and not as duplicates

**Additional context**
What's the point of search matching if you can't have routes whose only difference is their search match?

I realize this can be done, by leveraging `useSearch` within `<StepperContainer />` and showing the correct step based off the step param, but I was interested to see if it could be accomplished using search matching in the routes.

**Comment by mattdemichele-pearson** [comment]
I'd love to see this feature too. Ran into the same roadblock

**Comment by joshuabrokaw** [comment]
Looking through the source code a bit... 
```
    const recurseRoutes = (
      routes: Route<TGenerics>[],
      parent?: Route<TGenerics>,
    ): Route<TGenerics>[] => {
      return routes.map((route) => {
        const path = route.path ?? '*'

        const id = joinPaths([
          parent?.id === 'root' ? '' : parent?.id,
          `${path?.replace(/(.)\/$/, '$1')}${route.id ? `-${route.id}` : ''}`,
        ])

        route = {
          ...route,
          pendingMs: route.pendingMs ?? opts?.defaultPendingMs,
          pendingMinMs: route.pendingMinMs ?? opts?.defaultPendingMinMs,
          id,
        }

        if (this.routesById[id]) {
          if (process.env.NODE_ENV !== 'production') {
            console.warn('Duplicate routes found:', this.routesById[id], route)
          }
          throw new Error()
        }

        this.routesById[id] = route

        route.children = route.children?.length
          ? recurseRoutes(route.children, route)
          : undefined

        return route
      })
    }
```

 it seems routes are matched by their full path and then evaluated as a dupe based strictly on that. 

I think in order for this to work, you'd have to store the duplicates and then evaluate their search functions when matching maybe? Only throw that it's a dupe if no search match is provided. Not sure how you would validate uniqueness based off the search function, but maybe just when matching, return the first search match and it's on the user to guarantee uniqueness of their search matches?

**Comment by sb55555** [comment]
Hello we are using react-location for professional projects.
One of the projects needs modal routing through URLs.

We found a nice way of implementing this modal routing feature using react location
but on the last step we are blocked because 
**react location cannot handle multiple routes with the same path but different search functions**.

Here is a simple CodeSandBox to illustrate the issue, everything is in App.js,
[https://codesandbox.io/s/festive-khayyam-llbyo?file=/src/App.js](https://codesandbox.io/s/festive-khayyam-llbyo?file=/src/App.js)

We'd love to see this issue pushed forward to use this lib on all of our projects.
We're glad to help. Thank you

**Comment by tannerlinsley** [comment]
I originally intended the `route.id` property to be used for this exact purpose. Route IDs are used in the full path and full ID generation, so they would only need to be unique between siblings in this case:

```tsx
type LocationGenerics = MakeGenerics<{
  Search: {
    step?: number;
  };
}>;

const routes: Route<LocationGenerics>[] = [
  {
    path: "/stepper",
    element: <StepperContainer />,
    children: [
      {
        id: '0',
        search: (search) => {
          return search.step === 0;
        },
        element: <Step1 />,
      },
      {
        id: '1',
        search: (search) => {
          return search.step === 1;
        },
        element: <Step2 />,
      },
    ],
  },
];
```
