### ISSUE TITLE
Trailing slash is removed with navigate method

### ISSUE THREAD

**Issue by ka2jun8** [tannerlinsley/react-location#166]
**Describe the bug**

Even if it specified trailing slash for the next path `to` with `navigate` method param, it will be removed.

I understand there is no problem with react-location without trailing slash.
However, there might be cases where a trailing slash is intentionally used because filtering of trailing slash does not work as expected on the infrastructure or backend side, such as a log filtering.

If possible, I want `baseSegments.push(toSegment)` to be added in the following places, when there is trailing slash.

https://github.com/tannerlinsley/react-location/blob/v3.3.0/packages/react-location/src/index.tsx#L1881

**To Reproduce**
```
const navigate = useNavigate();
navigate({ to: "/sample/" });
```

**Expected behavior**
Trailing slash remains even after transition.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome

**Additional context**
`react-location: 3.3.0`

**Comment by Zauberfisch** [comment]
same seems to happen with `<Link to="/foo/">`. It renders as `<a href="/foo">`

**Comment by tannerlinsley** [comment]
Fixed in latest release 👍
