### ISSUE TITLE
`meta` is not returned in `useMatch`

### ISSUE THREAD

**Issue by vijaypushkin** [tannerlinsley/react-location#171]
### Discussed in https://github.com/tannerlinsley/react-location/discussions/170

<sup>Originally posted by **vijaypushkin** December 22, 2021</sup>

**Describe the bug**

TL;DR; `match.route` is returned as `null` from `useMatch` hook

Main reason for switching from `react-router` to `react-location` is to set page title and other meta details right at the routers file.
But for some reason, it is not usable

**To Reproduce**

```tsx

const location = new ReactLocation();

const routes = [
  {
    path: '/',
    index: true,
    element: <HomePage />,
    meta: {
      title: () => 'Home',
    },
  },
  {
    path: '/client',
    element: <ClientPage />,
    meta: {
      title: () => 'Client',
    },
   }
 ];
 
 const AppRouter: React.FC = (props) => {
  return (
    <Router location={location} routes={routes}>
      {props.children}
    </Router>
  );
};
```

Inside HomePage
```tsx
const match = useMatch();

console.log(match.route?.meta) // returns `null`, match.route is null
```

**Expected behavior**

`match.route.meta` should return `meta` object set in routes instead of `null` from `useMatch` hook

**Desktop (please complete the following information):**

    OS: macOS
    Browser: firefox

**Additional context**
`react-location: 3.3.0`

**Comment by joshuabrokaw** [comment]
If you look closely on in the [route definition](https://react-location.tanstack.com/docs/api#defining-routes) docs on line 49.

Notice the `meta?: UseGeneric<TGenerics, 'RouteMeta'>`

You have to tell react-location what the meta object looks like by doing something like this...

```
export type LocationGenerics = MakeGenerics<{
  RouteMeta: {
    title: string;
  };
}>;

const location = new ReactLocation<LocationGenerics>();

const routes: Route<LocationGenerics>[] = [
  {
    path: '/',
    index: true,
    element: <HomePage />,
    meta: {
      title: 'Home',
    },
  },
  {
    path: '/client',
    element: <ClientPage />,
    meta: {
      title: 'Client',
    },
   }
 ];

const AppRouter: React.FC = (props) => {
  return (
    <Router location={location} routes={routes}>
      {props.children}
    </Router>
  );
};
```

check out the [Kitchen Sink Example](https://react-location.tanstack.com/examples/kitchen-sink) for more details.

**Comment by vijaypushkin** [comment]
I just realised `useMatch` returns only the first element of `useMatches` results, which is not desirable. Is there a way get the last array from `useMatches` other than `matches[matches.length - 1]`?

**Comment by joshuabrokaw** [comment]
Not that I'm aware of.

**Comment by joshuabrokaw** [comment]
If you setup your routes correctly, `useMatch` should be giving you what the current route match is. Put your code in a codesandbox and I'll take a look.

**Comment by tannerlinsley** [comment]
If you still can't figure this out, create a new issue with a codesandbox we can reproduce your issue in. If you can't make a code-sandbox, then a discussion is sufficient.
