### ISSUE TITLE
Extracting an async route with children as a module does not work

### ISSUE THREAD

**Issue by skalidindi** [tannerlinsley/react-location#178]
**Describe the bug**
I want to extract an async nested route config to a separate file.

**To Reproduce**
See the following [sandbox](https://codesandbox.io/s/react-location-bug-l69zc?file=/src/index.tsx) for repro.
The sandbox is in a working state where the config is not extracted out. If you comment out the working block and uncomment out the block marked as uncomment where the config is extracted out in ClustersRoute.tsx, it does not work.

**Expected behavior**
I expect this...
```
{
  path: "clusters",
  children: [
    {
      path: "/",
      element: () =>
        import("./components/Clusters").then((module) => (
          <module.default />
        ))
    },
    {
      path: `:clusterId`,
      element: () =>
        import("./components/ClusterDetail").then((module) => (
          <module.default />
        ))
    }
  ]
}
```
to be replaced with
```
{
  path: "clusters",
  import: () =>
    import("./ClustersRoute").then((module) => module.default)
}
 ```

**Additional context**
```react-location: 3.3.0```

Note: Extracting an async route works when element is defined at the top level but things under children do not.

**Comment by joshuabrokaw** [comment]
Check out the definition of `import` in [Route API](https://react-location.tanstack.com/docs/api#defining-routes)

`{
     // If `import` is defined, this route can resolve its elements and loaders in a single asynchronous call
     // This is particularly useful for code-splitting or module federation
     import?: (opts: {
       params: UseGeneric<TGenerics, 'Params'>
       search: UseGeneric<TGenerics, 'Search'>
     }) => Promise<RouteLoaders<TGenerics>>
   }`

import is expecting a `Promise<RouteLoaders<TGenerics>>`, not `Promise<Route<TGenerics>[]>` which I think is what you were expecting.

**Comment by tannerlinsley** [comment]
Correct. You cannot extract actual route children or route paths to async code. There are reasons for this, most of them requiring that the entire route tree and their paths (at least) to be discoverable synchronously. Anything else can be extracted to async sources.
