### ISSUE TITLE
serverFn base url is hardcoded to localhost:3000

### ISSUE THREAD

**Issue by kandros** [tannerlinsley/react-location#2720]
### Which project does this relate to?

Start

### Describe the bug

https://github.com/tanstack/router/blob/cbc588dde615770891059186092fd030166370f0/packages/start/src/server-runtime/index.tsx#L87

This prevents using things serverFn URL property for progressive enhancement in production
https://tanstack.com/router/latest/docs/framework/react/start/server-functions#no-js-server-functions

**Comment by SeanCassiere** [comment]
The issue here is that the URL attached to the server function has the base of `http://localhost:3000` hardcoded into it. This should probably be stripped out and left as an absolute navigation, just without the URI as a part of the URL.

```ts
const $testFn = createServerFn().handler(async () => {
  await doSomething();
  return { foo: 'bar' }
})

console.log($testFn.url) // "http://localhost:3000/_server/?_serverFnId=xxxxxxxxx"

// should probably just be "/_server/?_serverFnId=xxxxxxxxx"
```
