### ISSUE TITLE
Link component ignore the basepath of LocationProvider

### ISSUE THREAD

**Issue by niboc** [tannerlinsley/react-location#3]
Could it be that you forgot to contemplate it? or maybe I'm missing something to make it work? I tried writing the basepath in all the ways

**LocationProvider**
```
<LocationProvider basepath="/subfolder/">
  <App />
</LocationProvider>
```
**Navbar**
```
<nav>
  <Link to="/">Home</Link>
  <Link to="/about-us">About Us</Link>
</nav>
```
When I click on a link, it goes to the root. The only way to make it work is to write the basepath in the "to" too, but it's not very practical.

**Navbar Working**
```
<nav>
  <Link to="/subfolder/">Home</Link>
  <Link to="/subfolder/about-us">About Us</Link>
</nav>
```

Thanks

**Comment by tannerlinsley** [comment]
This is definitely a big bug. That's supposed to work as you've
illustrated. I'll dig in and see what I can find.

**Comment by tannerlinsley** [comment]
Should be fixed in latest @next
