### ISSUE TITLE
SSR example does not work

### ISSUE THREAD

**Issue by kesne** [tannerlinsley/react-location#59]
**Describe the bug**
The SSR example in the API docs does not work as described. It looks like the API for `createMemoryHistory` is a little different (it expects `initialEntries`), and there's not clear where `loadMatches` is coming from in the code example.

Additionally, it seems like the router uses `useLayoutEffect`, which causes console warnings when trying to SSR.

**Comment by tannerlinsley** [comment]
I’m writing the updated SSR example currently.

**Comment by tannerlinsley** [comment]
I've dipped SSR into a (coming soon) state, so going to close this for now.
