### ISSUE TITLE
Example - Basic with React Query is throwing an error

### ISSUE THREAD

**Issue by burhanuday** [tannerlinsley/react-location#60]
**Describe the bug**
Example is crashing with an error
```
_reactLocation.useIsNextLocation is not a function
```

**To Reproduce**
1. Go to [Basic with react query example](https://react-location.tanstack.com/examples/basic-with-react-query)
2. See the sandbox that loads
3. See error

**Expected behavior**
Example should not crash

**Screenshots**
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/25934701/141604167-280f0436-5546-4b87-8f94-74ec2eb4ff07.png">

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - Browser: Firefox, Chrome
 - Version: 94

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by tannerlinsley** [comment]
Should be fixed now.
