### ISSUE TITLE
Example codesandbox results in a 404 in docs

### ISSUE THREAD

**Issue by PatrickDesign** [tannerlinsley/react-location#73]
**Describe the bug**
The example codesandbox results in a 404 on this page: https://react-location.tanstack.com/examples/basic.

Sandbox in question: https://codesandbox.io/s/github/tannerlinsley/react-location/tree/main/examples/basic

Update: after further investigation, it looks like all of the examples have broken sandboxes at the moment.

**Comment by tannerlinsley** [comment]
This is usually an upstream issue with Codesandbox. Every so often they get throttled from github clones (especially if a site is getting lots of traffic, like during a big release 😉 ). Looks like it's working again, at least for most of us.
