### ISSUE TITLE
Kitchen sink [Object object] in urlParams - [Examples]

### ISSUE THREAD

**Issue by jaszczw** [tannerlinsley/react-location#78]
**Describe the bug**

When viewing example of "Kitchen sink" the page Dashboard/Users - incorrectly serializes json state.

**To Reproduce**
1. Go to Dashboard
2. Click Users
3. See the url
4. Modify sort/filters, no effect on url

**Expected behavior**
The url should be properly serialized,deserialized.

**Screenshots**
![image](https://user-images.githubusercontent.com/1790627/142162462-33e80014-3e6e-4e60-8a4f-771cd1935576.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome
 - Version: 95
 
**Additional context**

**Comment by jaszczw** [comment]
I think:
https://github.com/tannerlinsley/react-location/blob/4e71890fb854ea6360fd7ea04db58ecc51f3e8bf/packages/react-location/src/index.tsx#L1871

This is responsible for this issue

**Comment by Suzan-Dev** [comment]
I tried the example by updating code as you commented and it is working for me as well. Also, the sorting and filtering functionalities are also working now.

**Comment by tannerlinsley** [comment]
Fixed in latest!
