### ISSUE TITLE
Using JSURL as in documentation leads to errors

### ISSUE THREAD

**Issue by jaszczw** [tannerlinsley/react-location#81]
**Describe the bug**
When adding JSURL references as explained in doc
```
import { ReactLocation } from 'react-location'
 import { parseSearch, stringifySearch } from 'react-location-jsurl'
 
 const reactLocation = new ReactLocation({
   parseSearch,
   stringifySearch,
 })
```

It actually adds the stringifiedSearch without `?` making it break the page.

Example
https://codesandbox.io/s/infallible-snowflake-rdq3u?file=/src/index.tsx

**To Reproduce**
1. Add reference to `react-location-jsurl`
2. Add usage of `parseSearch`, `stringifySearch`
3. See the navigation fail

**Expected behavior**
It should work all the same, as internally I see react-location uses react-location-jsurl, but it seems the API somehow changed.,

**Screenshots**
![image](https://user-images.githubusercontent.com/1790627/142170622-77d89957-5c01-414c-a6ac-659934be91ea.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome
 - Version: 95

**Comment by chidimo** [comment]
You should take a look at this issue. <https://github.com/tannerlinsley/react-location/issues/75>

My subsequent experience after that.

I installed version 3.1.10 and the error is still there.

I tried to install the commit with the fix with `yarn add https://github.com/tannerlinsley/react-location#66fab0a` but it throws the below error `error Can't add undefined: invalid package version undefined.`. I did some search and found that the error might be related to the fact that no version is specified in the `package.json` file.

**Comment by jaszczw** [comment]
The version on codesandbox is said to be 3.1.10 so the one that should include the fix.

**Comment by chidimo** [comment]
Yeah. But the bug is still present.

**Comment by tannerlinsley** [comment]
Fixed in the latest release :)
