### ISSUE TITLE
DependencyNotFoundError on Kitchen Sink example

### ISSUE THREAD

**Issue by Suzan-Dev** [tannerlinsley/react-location#86]
react-location-jsurl dependency is missing from the example.

**To Reproduce**
1. Go to the official react-location website.
2. See Kitchen Sink example.

**Expected behavior**
The example should work.

**Desktop (please complete the following information):**
 - OS: Fedora 34, Linux
 - Browser: Brave

**Comment by tannerlinsley** [comment]
Fixed!
