### ISSUE TITLE
__DEV__ global type declaration is included in package

### ISSUE THREAD

**Issue by sandervspl** [tannerlinsley/react-location#88]
**Describe the bug**
The global declaration of the const `__DEV__` is included in the package types (`index.d.ts`). This causes issues with my dev environment because I also have a global declaration for this exact variable. I don't think this is necessary or intended to be included. For now I can comment out my own declaration to solve the issue.

**To Reproduce**
1. Create a `declarations.d.ts` file
2. Add `declare const __DEV__: boolean;`
3. TypeScript should show an error: `Cannot redeclare block-scoped variable '__DEV__'.`

**Expected behavior**
This global development variable should not be included in the distributed package.

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15.7

**Additional context**
 - Editor: Visual Studio Code 1.62.1
 - TypeScript: 4.4.4

**Comment by tannerlinsley** [comment]
I've shipped an attempted fix in f018102d89d1796c16a4bce1b7451bd165bd5df1. Reopen if the problem persists!
