### ISSUE TITLE
Unable to user React Location Devtools with Vite

### ISSUE THREAD

**Issue by SandipNirmal** [tannerlinsley/react-location#96]
Unable to use `React Location Devtools` when using it in React app built with Vite. 

Getting following error

```
Failed to resolve entry for package "react-location-devtools". 
The package may have incorrect main/module/exports specified in its package.json: 
Failed to resolve entry for package "react-location-devtools". The package may have incorrect main/module
/exports specified in its package.json.

Plugin: vite:import-analysis
```

**Comment by kandhan-kuhan-t** [comment]
I imported from esmodule directory like this `import { ReactLocationDevtools } from "react-location-devtools/es/devtools"` and it works

**Comment by SandipNirmal** [comment]
> 

It works! Thanks.

**Comment by Domino987** [comment]
I am getting the error 
```
index.js:640 Uncaught Error
    at useRouter
```
and 
```
react_devtools_backend.js:2540 Warning: Invalid DOM property `fill-rule`. Did you mean `fillRule`?
```
using vite and the `import { ReactLocationDevtools } from "react-location-devtools/es/devtools"` import.
 Do you mind sharing your setup so I can see why mine does not work?

**Comment by ToniMaunde** [comment]
Hi. My Vite project doesn't even have the react-location-devtools in the node_modules. Any ideas on that?
